name: SonarCloud

on:
  pull_request:
    branches: [ master ]

jobs:

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
      - uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          